### ISSUE TITLE
Misleading message for ci-checker

### ISSUE THREAD

**Issue by ankitrm** [traveloka/codebuild-terraform-ci-cd-image#29]
ci-checker error message in case feature is not based out of latest master commit:
```
[Container] 2019/03/11 10:32:11 Running command . ci-check.sh
Error: Commit isn't based on origin/master
 [Container] 2019/03/11 10:32:11 Command did not exit successfully . ci-check.sh exit status 1
[Container] 2019/03/11 10:32:11 Phase complete: PRE_BUILD Success: false
[Container] 2019/03/11 10:32:11 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: . ci-check.sh. Reason: exit status 1
```

The error message: `Commit isn't based on origin/master` is misleading. We need to improve error message to something like `Feature branch is behind the latest master branch commit. Please rebase/add merge commit from master to your feature branch` which depicts the issue as well as action needed to be performed.

**Comment by karstenaa** [comment]
Thanks @ankitrm. Could you elaborate more on what is misleading?Just in case I miss something fundamental.
I agree that follow up solution should be given on error message. Would you mind create a PR to fix this issue? Error message is on https://github.com/traveloka/codebuild-terraform-ci-cd-image/blob/master/scripts/ci-check.sh

**Comment by ankitrm** [comment]
Thanks @karstenaa for looking into it. There is nothing missing fundamentally, it's just that a couple of us spent maybe an hour to figure out what the basic problem is due to error message not being very clear. We thought maybe our base branch is wrong (which was master) or if we need to do a force push every time we check-in (weird but yes), so I have opened up a PR for your review.
https://github.com/traveloka/codebuild-terraform-ci-cd-image/pull/30
Thanks again for helping us!

**Comment by karstenaa** [comment]
merged to master. :bow:
